CREATE TABLE `spring`.`account`(
  `ID` BIGINT(20) NOT NULL COMMENT '主键',
  `NAME` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '名称',
  `MONEY` DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '金额',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `account` (`ID`, `NAME`, `MONEY`) VALUES (1, 'JACK', 600);
INSERT INTO `account` (`ID`, `NAME`, `MONEY`) VALUES (2, 'TOM', 2400);
